title: FSA Farm Payment Files
description: Official farm payment files from the USDA Farm Service Agency, 2004–2024
author: R. Kyle Bocinsky
url: "https://climate-smart-usda.github.io/fsa-payment-files/"  # Your GitHub Pages URL
baseurl: "/fsa-payment-files"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# minima:
#   skin: classic